= Nirvarnia Decision Log

This repository is a record of the major technical decisions taken in developing Nirvarnia.

The primary purpose of the decision log is to record architecturally-significant design choices. It also records choices of automation tools, coding conventions, workflow strategies including branching-and-merging, testing and release, and other development concerns.

Each discrete decision is recorded in a single text file.

== Contributing

Anyone can contribute to the technical direction of the Nirvarnia project by creating new design documents. Follow these steps:

1. Fork this repository into your personal or organization account on GitHub. (Maintainers with write access to the reference repository MAY skip this step.)
2. Branch off `main` using the naming convention `proposal/[hyphen-delimited-slug]`.
3. Copy the `TEMPLATE.adoc` file into the `proposed` directory. Rename the copied file to match `[hyphen-delimited-slug].adoc`. Edit the document's title and change its status to *PROPOSED*.
4. You MAY edit the design document to flesh out your thoughts in more detail. This step is OPTIONAL.
5. Commit and push your changes. Open a pull request to merge your proposal into the `main` branch of the reference repository. Copy the title of your design document into the title of the PR, and write a short summary of the proposal in the description field.

The process of opening a pull request initializes a *Request for Comments (RFC)* process in which the proposal is negotiated with the project's maintainers and other stakeholders.

NOTE: The issue tracker attached to this repository SHOULD NOT be used to propose new design documents. The issue tracker SHOULD be used only to propose changes to the RFC process itself. The pull request system is used for the normal RFC workflow.

The outcome of the RFC process will, normally, be for the design document to be merged into the upstream reference repository. After merging, the maintainers may make further edits to the design before, ultimately, changing its status to either *ACCEPTED* or *REJECTED*.

When a proposal is accepted, the maintainers will start tickets to track the implementation. The tickets will be linked from the design document. Finally, when the implementation is complete, the status of the design document will be changed to *IMPLEMENTED*.

The same steps are followed to change past decisions. However, once a proposed solution is implemented in code and configuration, the design document is thereafter treated as immutable. Therefore, to change or revert past decisions, new documents must be appended to the log that supersede the old ones. The status of the original decisions can then be changed to *DEPRECATED*.

=== Contributor license agreement

By opening a pull request to this repository, you accept and agree to the following terms and conditions:

* You agree that your contribution may be distributed under the terms of the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

* You certify that your contribution is either created in whole by you and you have the right to distribute the work under the designated license, or is based on a previous work with a similar license that permits distribution and modification under the designated license.

* You understand and agree that your contribution is public and that a record of the contribution, including all personal information that you submit with it, is maintained indefinitely and may be redistributed as per the requirements of the designated license.

'''

© https://github.com/nirvarnia/decisions/graphs/contributors[Contributors] | link:LICENSE.txt[CC BY 4.0]
