= Nirvarnia Decision Log

This repository is a record of the major technical decisions taken in developing Nirvarnia.

The primary purpose of the decision log is to record architecturally-significant design choices. It also records choices of automation tools, coding conventions, workflow strategies including branching-and-merging, testing and release, and other development concerns.

Each discrete decision is recorded in a single text file.

== Contributing

Anyone can contribute to the technical direction of the Nirvarnia project by creating new decision documents. Follow these steps:

1. Fork this repository into your personal or organization account on GitHub. (Maintainers with write access to the reference repository MAY skip this step.)
2. Branch off `dev` using the naming convention `proposal/[hyphen-delimited-slug]`.
3. Copy the `TEMPLATE.adoc` file into the `proposed` directory. Rename the copied file to match `[hyphen-delimited-slug].adoc`. Edit the document's title and change its status to *PROPOSED*.
4. You MAY edit the proposal document to flesh out your thoughts in more detail. This step is OPTIONAL.
5. Commit and push your changes. Open a pull request to merge your proposal into the `dev` branch of the reference repository. Copy the title of your proposal document into the title of the PR, and write a short summary of the proposal in the description field.

The process of opening a pull request initializes a *Request for Comments (RFC)* process in which the proposal is negotiated with the project's maintainers and other stakeholders.

The outcome of the RFC process will, normally, be for the proposal document to be merged into the upstream reference repository. After merging, the maintainers may make further edits to a proposal before, ultimately, changing its status to either *ACCEPTED* or *REJECTED*.

When a proposal is accepted, the maintainers will start tickets to track the implementation. The tickets will be linked from the proposal document. Finally, when the implementation is complete, the status of the proposal document will be changed to *IMPLEMENTED*.

The same steps are followed to change past decisions. However, once a proposed solution is implemented in code and configuration, the decision document is thereafter treated as immutable. Therefore, to change or revert past decisions, new documents must be added to the log that supersede the old ones. The status of the original decisions can then be changed to *DEPRECATED*.
